---
- name: Per-user group creation
  group: name="{{ item.name }}" gid="{{ (item.gid | default(item.uid)) | default(omit) }}"
  with_items: "{{ users_users }}"
  when: "{{ 'group' not in item and users_group_per_user }}"

- name: Create users
  user:
    name: "{{ item.name }}"
    group: "{{ item.group|default(item.name if users_group_per_user else users_group) }}"
    groups: "{{ (item.groups|default([]) + item.sudo|default(False)|ternary(['sudo'],[]))|join(',') }}"
    shell: "{{ (item.shell|default(users_shell))|default(omit) }}"
    createhome: "{{ item.createhome|default(omit) }}"
    comment: "{{ item.comment|default(omit) }}"
  with_items: "{{ users_users }}"

- name: Add authorized ssh key
  authorized_key: user={{ item.0.name }} key="{{ item.1 }}"
  become: yes
  become_user: "{{ item.0.name }}"
  with_subelements:
    - "{{ users_users }}"
    - authorized
    - flags:
      skip_missing: true

- name: Add dotfiles blocks
  become: yes
  become_user: "{{ item.0.name }}"
  blockinfile:
    dest: "{{ item.1.file }}"
    block: "{{ item.1.block }}"
    owner: "{{ item.0.name }}"
    marker: "#{mark} {{ item.1.marker|default('') }}"
    mode: 0644
    create: true
  with_subelements:
    - "{{ users_users }}"
    - dotfiles
    - flags:
      skip_missing: true

- name: Add sudo users
  template: src=etc/sudoers.d/sudo.j2 dest=/etc/sudoers.d/{{ item.name }} owner=root group=root mode=0440 force=yes
  with_items: "{{ users_users }}"
